config/routes.rb
Rails.application.routes.draw do
  
  resources :sponsors
  resources :photos
  resources :albums
  resources :events
  resources :pages
  get 'site/home'
  get 'site/event'
  get 'site/page'
  get 'site/photo'
  get 'site/sponsor'
  get 'site/contact'
  devise_for :members
  resources :sections

  root 'site#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/section.rb
class Section < ApplicationRecord
	has_many :pages
end

app/controllers/sections_controller.rb
class SectionsController < ApplicationController
  before_action :set_section, only: %i[ show edit update destroy ]
  before_action :authenticate_member!

  # GET /sections or /sections.json
  def index
    @sections = Section.all
  end

  # GET /sections/1 or /sections/1.json
  def show
  end

  # GET /sections/new
  def new
    @section = Section.new
  end

  # GET /sections/1/edit
  def edit
  end

  # POST /sections or /sections.json
  def create
    @section = Section.new(section_params)

    respond_to do |format|
      if @section.save
        format.html { redirect_to @section, notice: "Section was successfully created." }
        format.json { render :show, status: :created, location: @section }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @section.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /sections/1 or /sections/1.json
  def update
    respond_to do |format|
      if @section.update(section_params)
        format.html { redirect_to @section, notice: "Section was successfully updated." }
        format.json { render :show, status: :ok, location: @section }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @section.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sections/1 or /sections/1.json
  def destroy
    @section.destroy
    respond_to do |format|
      format.html { redirect_to sections_url, notice: "Section was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_section
      @section = Section.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def section_params
      params.require(:section).permit(:location, :title, :visible, :position)
    end
end

app/helpers/sections_helper.rb
module SectionsHelper
end

app/views/sections/_form.html.erb
<%= form_with(model: section) do |form| %>
  <% if section.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(section.errors.count, "error") %> prohibited this section from being saved:</h2>

      <ul>
        <% section.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field my-3">
    <%= form.label :location, class: "form-label" %>
    <%= form.text_field :location, class: "form-control" %>
  </div>

  <div class="field my-3">
    <%= form.label :title, class: "form-label" %>
    <%= form.text_field :title, class: "form-control" %>
  </div>

  <div class="field my-3">
    <%= form.label :visible, class: "form-check-label"%>
    <%= form.check_box :visible, class: "form-check-input" %>
  </div>

  <div class="field my-3">
    <%= form.label :position, class: "form-label"%>
    <%= form.number_field :position, class: "form-control" %>
  </div>

  <div class="actions my-3">
    <%= form.submit class:  "btn btn-dark" %>
  </div>
<% end %>

app/views/sections/edit.html.erb
<div class="container bg_white p-5">

  <div class="row">
  	<div class="col-12">
  	  <h1>New Section</h1>

	  <%= render 'form', section: @section %>

	  <%= link_to 'Show', @section, class: "btn btn-dark"  %> |
	  <%= link_to 'Back', sections_path, class: "btn btn-dark"  %>
  	</div>
  </div>

</div>

app/views/sections/index.html.erb
<div class="container bg_white p-5">

  <p id="notice"><%= notice %></p>

  <div class="row">
    
    <h1 class=col-12>Sections</h1>

    <div class="col-12" text center>
      <table>
        <thead>
          <tr>
            <th class="pe-3" >Location</th>
            <th class="pe-3" >Title</th>
            <th class="pe-3" >Visible</th>
            <th class="pe-3" >Position</th>
            <th colspan="3"></th>
          </tr>
        </thead>

        <tbody>
          <% @sections.each do |section| %>
            <tr class="">
              <td class="pt-3 pe-3" ><%= section.location %></td>
              <td class="pt-3 pe-3" ><%= section.title %></td>
              <td class="pt-3 pe-3" ><%= section.visible %></td>
              <td class="pt-3 pe-3" ><%= section.position %></td>
              <td class="pt-3 pe-3" ><%= link_to 'Show', section , class: "btn btn-dark" %></td>
              <td class="pt-3 pe-3" ><%= link_to 'Edit', edit_section_path(section), class: "btn btn-dark" %></td>
              <td class="pt-3 pe-3" ><%= link_to 'Destroy', section, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-dark" %></td>
            </tr>
          <% end %>
        </tbody>
      </table>

      <br>

      <%= link_to 'New Section', new_section_path, class: "btn btn-dark" %>
    </div>

  </div>

</div>

app/views/sections/new.html.erb
<div class="container bg_white p-5">

  <div clas="row">
    <div class="col-12">
      <h1>New Section</h1>

	  <%= render 'form', section: @section %>

	  <%= link_to 'Back', sections_path, class: "btn btn-dark"  %>
    </div>
  </div>

</div>

app/views/sections/show.html.erb
<div class="container bg_white p-5">

  <div clas="row">
    <div class="col-12">
      <p id="notice"><%= notice %></p>

      <p>
        <strong>Location:</strong>
        <%= @section.location %>
      </p>

      <p>
        <strong>Title:</strong>
        <%= @section.title %>
      </p>

      <p>
        <strong>Visible:</strong>
        <%= @section.visible %>
      </p>

      <p>
        <strong>Position:</strong>
        <%= @section.position %>
      </p>

      <%= link_to 'Edit', edit_section_path(@section), class: "btn btn-dark" %> |
      <%= link_to 'Back', sections_path, class: "btn btn-dark" %>
    </div>
  </div>

</div>