config/routes.rb
Rails.application.routes.draw do
  
  resources :sponsors
  resources :photos
  resources :albums
  resources :events
  resources :pages
  get 'site/home'
  get 'site/event'
  get 'site/page'
  get 'site/photo'
  get 'site/sponsor'
  get 'site/contact'
  devise_for :members
  resources :sections

  root 'site#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/sponsor.rb
class Sponsor < ApplicationRecord
	has_one_attached :photo
end

app/controllers/sponsors_controller.rb
class SponsorsController < ApplicationController
  before_action :set_sponsor, only: %i[ show edit update destroy ]
  before_action :authenticate_member!

  # GET /sponsors or /sponsors.json
  def index
    @sponsors = Sponsor.all
  end

  # GET /sponsors/1 or /sponsors/1.json
  def show
  end

  # GET /sponsors/new
  def new
    @sponsor = Sponsor.new
  end

  # GET /sponsors/1/edit
  def edit
  end

  # POST /sponsors or /sponsors.json
  def create
    @sponsor = Sponsor.new(sponsor_params)

    respond_to do |format|
      if @sponsor.save
        format.html { redirect_to @sponsor, notice: "Sponsor was successfully created." }
        format.json { render :show, status: :created, location: @sponsor }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @sponsor.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /sponsors/1 or /sponsors/1.json
  def update
    respond_to do |format|
      if @sponsor.update(sponsor_params)
        format.html { redirect_to @sponsor, notice: "Sponsor was successfully updated." }
        format.json { render :show, status: :ok, location: @sponsor }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @sponsor.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sponsors/1 or /sponsors/1.json
  def destroy
    @sponsor.destroy
    respond_to do |format|
      format.html { redirect_to sponsors_url, notice: "Sponsor was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_sponsor
      @sponsor = Sponsor.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def sponsor_params
      params.require(:sponsor).permit(:title, :photo, :website)
    end
end

app/helpers/sponsors_helper.rb
module SponsorsHelper
end

app/views/sponsors/_form.html.erb
<%= form_with(model: sponsor) do |form| %>
  <% if sponsor.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(sponsor.errors.count, "error") %> prohibited this sponsor from being saved:</h2>

      <ul>
        <% sponsor.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field my-3">
    <%= form.label :title , class: "form-label"%>
    <%= form.text_field :title, class: "form-control"%>
  </div>

  <div class="field my-3">
    <%= form.label :photo %>
    <%= form.file_field :photo %>
  </div>

  <div class="field my-3">
    <%= form.label :website , class: "form-label"%>
    <%= form.text_field :website, class: "form-control" %>
  </div>

  <div class="actions my-3">
    <%= form.submit  class:  "btn btn-dark" %>
  </div>
<% end %>

app/views/sponsors/edit.html.erb
<div class="container bg_white p-5">

  <div class="row">
  	<div class="col-12">
  	  <h1>Editing Sponsor</h1>

	  <%= render 'form', sponsor: @sponsor %>

	  <%= link_to 'Show', @sponsor , class: "btn btn-dark" %> |
	  <%= link_to 'Back', sponsors_path , class: "btn btn-dark" %>
  	</div>
  </div>

</div>

app/views/sponsors/index.html.erb
<div class="container bg_white p-5">

  <p id="notice"><%= notice %></p>

  <div class="row">
    
    <h1 class=col-12>Sponsors</h1>

    <div class="col-12" text center>
      <table>
      <thead>
        <tr>
          <th class="pt-3 pe-3">Title</th>
          <th class="pt-3 pe-3">Website</th>
          <th colspan="3"></th>
        </tr>
      </thead>

      <tbody>
        <% @sponsors.each do |sponsor| %>
          <tr>
            <td class="pt-3 pe-3"><%= sponsor.title %></td>
            <td class="pt-3 pe-3"><%= sponsor.website %></td>
            <td class="pt-3 pe-3"><%= link_to 'Show', sponsor ,  class: "btn btn-dark"%></td>
            <td class="pt-3 pe-3"><%= link_to 'Edit', edit_sponsor_path(sponsor),  class: "btn btn-dark" %></td>
            <td class="pt-3 pe-3"><%= link_to 'Destroy', sponsor, method: :delete, data: { confirm: 'Are you sure?' },  class: "btn btn-dark" %></td>
          </tr>
        <% end %>
      </tbody>
    </table>


      <br>

      <%= link_to 'New Sponsor', new_sponsor_path,  class: "btn btn-dark" %>
    </div>

  </div>

</div>

app/views/sponsors/new.html.erb
<div class="container bg_white p-5">

  <div class="row">
  	<div class="col-12">
  	  <h1>Editing Sponsor</h1>

	  <%= render 'form', sponsor: @sponsor %>

	  <%= link_to 'Back', sponsors_path , class: "btn btn-dark" %>
  	</div>
  </div>

</div>

app/views/sponsors/show.html.erb
<div class="container bg_white p-5">

  <div clas="row">
    <div class="col-12">
      <p id="notice"><%= notice %></p>

      <p>
        <strong>Title:</strong>
        <%= @sponsor.title %>
      </p>

      <% if @sponsor.photo.attached?%>
        <%= image_tag @sponsor.photo %>
      <% end %>

      <p>
        <strong>Website:</strong>
        <%= @sponsor.website %>
      </p>

      <%= link_to 'Edit', edit_sponsor_path(@sponsor), class: "btn btn-dark" %> |
      <%= link_to 'Back', sponsors_path, class: "btn btn-dark" %>
    </div>
  </div>

</div>