config/routes.rb
Rails.application.routes.draw do
  
  resources :sponsors
  resources :photos
  resources :albums
  resources :events
  resources :pages
  get 'site/home'
  get 'site/event'
  get 'site/page'
  get 'site/photo'
  get 'site/sponsor'
  get 'site/contact'
  devise_for :members
  resources :sections

  root 'site#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/album.rb
class Album < ApplicationRecord
	has_many :photos
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/event.rb
class Event < ApplicationRecord
	has_one_attached :photo
end

app/models/member.rb
class Member < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/page.rb
class Page < ApplicationRecord
	belongs_to :section
end

app/models/photo.rb
class Photo < ApplicationRecord
	has_one_attached :photo
	belongs_to :album
end

app/models/section.rb
class Section < ApplicationRecord
	has_many :pages
end

app/models/sponsor.rb
class Sponsor < ApplicationRecord
	has_one_attached :photo
end

app/controllers/albums_controller.rb
class AlbumsController < ApplicationController
  before_action :set_album, only: %i[ show edit update destroy ]
  before_action :authenticate_member!

  # GET /albums or /albums.json
  def index
    @albums = Album.all
  end

  # GET /albums/1 or /albums/1.json
  def show
  end

  # GET /albums/new
  def new
    @album = Album.new
  end

  # GET /albums/1/edit
  def edit
  end

  # POST /albums or /albums.json
  def create
    @album = Album.new(album_params)

    respond_to do |format|
      if @album.save
        format.html { redirect_to @album, notice: "Album was successfully created." }
        format.json { render :show, status: :created, location: @album }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @album.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /albums/1 or /albums/1.json
  def update
    respond_to do |format|
      if @album.update(album_params)
        format.html { redirect_to @album, notice: "Album was successfully updated." }
        format.json { render :show, status: :ok, location: @album }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @album.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /albums/1 or /albums/1.json
  def destroy
    @album.destroy
    respond_to do |format|
      format.html { redirect_to albums_url, notice: "Album was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_album
      @album = Album.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def album_params
      params.require(:album).permit(:title, :description)
    end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: %i[ show edit update destroy ]
  before_action :authenticate_member!

  # GET /events or /events.json
  def index
    @events = Event.all
  end

  # GET /events/1 or /events/1.json
  def show
  end

  # GET /events/new
  def new
    @event = Event.new
  end

  # GET /events/1/edit
  def edit
  end

  # POST /events or /events.json
  def create
    @event = Event.new(event_params)

    respond_to do |format|
      if @event.save
        format.html { redirect_to @event, notice: "Event was successfully created." }
        format.json { render :show, status: :created, location: @event }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /events/1 or /events/1.json
  def update
    respond_to do |format|
      if @event.update(event_params)
        format.html { redirect_to @event, notice: "Event was successfully updated." }
        format.json { render :show, status: :ok, location: @event }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1 or /events/1.json
  def destroy
    @event.destroy
    respond_to do |format|
      format.html { redirect_to events_url, notice: "Event was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_event
      @event = Event.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def event_params
      params.require(:event).permit(:title, :details, :photo)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  before_action :set_page, only: %i[ show edit update destroy ]
  before_action :authenticate_member!

  # GET /pages or /pages.json
  def index
    @pages = Page.all
  end

  # GET /pages/1 or /pages/1.json
  def show
  end

  # GET /pages/new
  def new
    @page = Page.new
  end

  # GET /pages/1/edit
  def edit
  end

  # POST /pages or /pages.json
  def create
    @page = Page.new(page_params)

    respond_to do |format|
      if @page.save
        format.html { redirect_to @page, notice: "Page was successfully created." }
        format.json { render :show, status: :created, location: @page }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @page.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pages/1 or /pages/1.json
  def update
    respond_to do |format|
      if @page.update(page_params)
        format.html { redirect_to @page, notice: "Page was successfully updated." }
        format.json { render :show, status: :ok, location: @page }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @page.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pages/1 or /pages/1.json
  def destroy
    @page.destroy
    respond_to do |format|
      format.html { redirect_to pages_url, notice: "Page was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_page
      @page = Page.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def page_params
      params.require(:page).permit(:title, :section_id, :page_type, :permalink, :visible, :position, :content, :destination)
    end
end

app/controllers/site_controller.rb
class SiteController < ApplicationController
  def home
  end

  def page
    @page = Page.find(params[:id])
  end
  
  def event
    @events = Event.all
  end

  def photo
    @albums = Album.all
  end

  def sponsor
    @sponsors = Sponsor.all
  end

  def contact
    
  end
end

app/helpers/albums_helper.rb
module AlbumsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/helpers/sections_helper.rb
module SectionsHelper
end

app/helpers/site_helper.rb
module SiteHelper
end

app/helpers/sponsors_helper.rb
module SponsorsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Club</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
     <%= tinymce_assets %>
    <script type="text/javascript" src="/assets/tinymce.js"></script>

  
  </head>

  <body>

    <header>

      <nav class="navbar navbar-expand-lg navbar-dark">
        <div class="container-fluid">
          <a class="navbar-brand" href="#"><%= image_tag "harmony_club.png", id: "logo" %><h1 class="d-inline-block ms-3"><%= link_to "Harmony Club of Worcester", site_home_url, class: "navbar-brand" %></h1></a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="d-flex navbar-nav ms-auto mb-2 mb-lg-0 me-5">

              <% @sections.each do |sec| %>
                <li class="nav-item dropdown me-4">
                  <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                   <%= sec.title %>
                  </a>
                  <ul class="dropdown-menu" aria-labelledby="navbarDropdown">

                    <% sec.pages.each do |page| %>
                      <% if page.page_type == "Basic Page" %>
                        <li><%= link_to page.title, site_page_path(id: page.id), class: "dropdown-item" %></li>
                      <% elsif page.page_type == "Internal URL" %>
                        <li><%= link_to page.title, page.destination, class: "dropdown-item" %></li>
                      <% elsif page.page_type == "External URL" %>
                        <li><%= link_to page.title, page.permalink, class: "dropdown-item", target: :_blank %></li>
                      <% end %>
                    <% end %>

                  </ul>
                </li>
              <% end %>

            </ul>
          </div>
          <p class="notice"><%= notice %></p>
          <p class="alert"><%= alert %></p>
        </div>
      </nav>
    </header>

    <main>
      <%= yield %>
    </main>

    <footer class="bg_black mx-0 p-5">
      <div class="row">
        <div class="col-12 text-end text_white">
          Harmony Club of Worcester, MA
        </div>
      </div>
    </footer>

  </body>
</html>

app/views/pages/_form.html.erb
<%= form_with(model: page) do |form| %>
  <% if page.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(page.errors.count, "error") %> prohibited this page from being saved:</h2>

      <ul>
        <% page.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field my-3">
    <%= form.label :title , class: "form-label"%>
    <%= form.text_field :title , class: "form-control"%>
  </div>

  <div class="field my-3">
    <%= form.label :section_id , class: "form-label"%>
    <%= form.number_field :section_id , class: "form-control"%>
  </div>

  <div class="field my-3">
    <%= form.label :page_type , class: "form-label"%>
    <%= form.text_field :page_type, class: "form-control" %>
  </div>

  <div class="field my-3">
    <%= form.label :permalink , class: "form-label"%>
    <%= form.text_field :permalink, class: "form-control" %>
  </div>

  <div class="field my-3">
    <%= form.label :visible , class: "form-check-label"%>
    <%= form.check_box :visible, class: "form-check-label" %>
  </div>

  <div class="field my-3">
    <%= form.label :position , class: "form-label"%>
    <%= form.number_field :position, class: "form-control" %>
  </div>

  <div class="field my-3">
    <%= form.label :content , class: "form-label"%>
    <%= form.text_area :content, class: "form-control tinymce" %>
  </div>

  <div class="field my-3">
    <%= form.label :destination , class: "form-label"%>
    <%= form.text_area :destination, class: "form-control" %>
    <%= tinymce %>
  </div>

  <div class="actions my-3">
    <%= form.submit  class:  "btn btn-dark" %>
  </div>
<% end %>

app/views/pages/edit.html.erb
<div class="container bg_white p-5">

  <div class="row">
  	<div class="col-12">
  	  <h1>Editing Page</h1>

		<%= render 'form', page: @page %>

		<%= link_to 'Show', @page , class: "btn btn-dark" %> |
		<%= link_to 'Back', pages_path , class: "btn btn-dark" %>
  	</div>
  </div>

</div>

app/views/pages/index.html.erb
<div class="container bg_white p-5">

  <p id="notice"><%= notice %></p>

  <div class="row">
    
    <h1 class=col-12>Pages</h1>

    <div class="col-12" text center>
      <table>
        <thead>
          <tr>
            <th class="pe-3">Title</th>
            <th class="pe-3">Section</th>
            <th class="pe-3">Page type</th>
            <th class="pe-3">Permalink</th>
            <th class="pe-3">Visible</th>
            <th class="pe-3">Position</th>
            <th class="pe-3">Content</th>
            <th colspan="3"></th>
          </tr>
        </thead>

        <tbody>
          <% @pages.each do |page| %>
            <tr>
              <td class="pt-3 pe-3"><%= page.title %></td>
              <td class="pt-3 pe-3"><%= page.section_id %></td>
              <td class="pt-3 pe-3"><%= page.page_type %></td>
              <td class="pt-3 pe-3"><%= page.permalink %></td>
              <td class="pt-3 pe-3"><%= page.visible %></td>
              <td class="pt-3 pe-3"><%= page.position %></td>
              <td class="pt-3 pe-3"><%= page.content %></td>
              <td class="pt-3 pe-3"><%= link_to 'Show', page , class: "btn btn-dark"%></td>
              <td class="pt-3 pe-3"><%= link_to 'Edit', edit_page_path(page), class: "btn btn-dark" %></td>
              <td class="pt-3 pe-3"><%= link_to 'Destroy', page, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-dark" %></td>
            </tr>
          <% end %>
        </tbody>
      </table>

      <br>

      <%= link_to 'New Page', new_page_path,  class: "btn btn-dark" %>
    </div>

  </div>

</div>

app/views/pages/new.html.erb
<div class="container bg_white p-5">

  <div class="row">
  	<div class="col-12">
  	  <h1>Editing Page</h1>

		<%= render 'form', page: @page %>

		<%= link_to 'Back', pages_path , class: "btn btn-dark" %>
  	</div>
  </div>

</div>

app/views/pages/show.html.erb
<div class="container bg_white p-5">

  <div clas="row">
    <div class="col-12">
      <p id="notice"><%= notice %></p>

      <p>
        <strong>Title:</strong>
        <%= @page.title %>
      </p>

      <p>
        <strong>Section:</strong>
        <%= @page.section_id %>
      </p>

      <p>
        <strong>Page type:</strong>
        <%= @page.page_type %>
      </p>

      <p>
        <strong>Permalink:</strong>
        <%= @page.permalink %>
      </p>

      <p>
        <strong>Visible:</strong>
        <%= @page.visible %>
      </p>

      <p>
        <strong>Position:</strong>
        <%= @page.position %>
      </p>

      <p>
        <strong>Content:</strong>
        <%= @page.content %>
      </p>

      <p>
        <strong>Destination:</strong>
        <%= @page.destination %>
      </p>

      <%= link_to 'Edit', edit_page_path(@page), class: "btn btn-dark"  %> |
      <%= link_to 'Back', pages_path , class: "btn btn-dark" %>
    </div>
  </div>

</div>